# Prod Terraform Backend Environment Variables

variables:
- name: environment
  value: 'prod'

- name: suffix
  value: '01'

- name: subscriptionId
  value: '#TODO: Fill in subscription Id'

- template: common.yml
